version: '3.8'

services:
  
  redis:
    image: redis:7-alpine
    container_name: lxc_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  
  web:
    build: .
    container_name: lxc_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    
  worker:
    build: .
    container_name: lxc_worker
    volumes:
      - .:/app
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - lxc_data:/var/lib/lxc
    depends_on:
      - redis
    command: celery -A worker.celery_app worker --loglevel=info
    restart: unless-stopped
    privileged: true


volumes:
  lxc_data:
